global:
  scrape_interval: 5s # Ambil data setiap 5 detik

scrape_configs:
  # Job 1: Ambil data dari Exporter Python kita tadi
  - job_name: 'ml_model_exporter'
    static_configs:
      - targets: ['localhost:8000']