name: Churn Prediction Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Ambil kodingan dari GitHub
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Siapkan Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
        # Saran: Pake 3.10 aja yang lebih stabil buat MLflow, 3.12 kadang rewel sama library lama.

    # 3. Install Library
    - name: Install Dependencies
      run: |
        pip install mlflow pandas scikit-learn matplotlib seaborn
        # Gak perlu install dagshub kalau di script python udah gak dipake

    # 4. Jalankan MLflow Project (Training)
    - name: Run Training Experiment
      run: | 
        cd Workflow-CI/MLProject
        mlflow run . --experiment-name Eksperimen_CI_Docker --env-manager=local

    # =========================================
    # BAGIAN DOCKER (KRITERIA 3)
    # =========================================

    # 5. Login ke Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 6. Build & Push Image
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        # INI YANG TADI SALAH (Hapus "cd"-nya)
        context: Workflow-CI/MLProject
        push: true
        
        tags: elsa88/churn-prediction:latest


        # fix docker username to elsa88