name: Churn Prediction Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Ambil kodingan dari GitHub
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Siapkan Python
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Install Library
    - name: Install Dependencies
      run: |
        pip install mlflow dagshub pandas scikit-learn matplotlib seaborn

    # 4. Jalankan MLflow Project (Training)
    - name: Run Training Experiment
      env:
        MLFLOW_TRACKING_URI: 'https://dagshub.com/elsaamundi/submission-sml-elsa.mlflow'
        MLFLOW_TRACKING_USERNAME: '${{ secrets.DAGSHUB_USERNAME }}'
        MLFLOW_TRACKING_PASSWORD: '${{ secrets.DAGSHUB_TOKEN }}'
        DAGSHUB_USER_TOKEN: '${{ secrets.DAGSHUB_TOKEN }}'
      run: |
        cd Workflow-CI/MLProject
        mlflow run . --env-manager=local

    # =========================================
    # BAGIAN BARU (DOCKER) MULAI DARI SINI
    # =========================================

    # 5. Login ke Docker Hub (Pakai Secret yang barusan dibuat)
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Ini ngambil "elsa88"
        password: ${{ secrets.DOCKER_PASSWORD }}  # Ini ngambil Token 

    # 6. Build & Push Image
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        # GANTI TITIK JADI NAMA FOLDER INI:
        context: Workflow-CI/MLProject
        push: true
        tags: elsa88/churn-prediction:latest
