name: Churn Prediction Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    
    steps:
    # 1.  kodingan dari GitHub
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2.  Python
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Install Library
    - name: Install Dependencies
      run: |
        pip install mlflow dagshub pandas scikit-learn matplotlib seaborn

    # 4.  MLflow Project
    - name: Run Training Experiment
      env:
        MLFLOW_TRACKING_URI: https://dagshub.com/elsaamundi/submission-sml-elsa.mlflow
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        cd Workflow-CI/MLProject
        mlflow run . --no-conda